# Generated by Django 5.1.7 on 2025-03-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_enseignant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.DateField()),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=20)),
                ('nb_creneaux', models.IntegerField(default=5)),
                ('exception', models.BooleanField(default=False)),
                ('creneaux_exceptionnels', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContrainteHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10)),
                ('creneau', models.CharField(choices=[('P1', 'Période 1'), ('P2', 'Période 2'), ('P3', 'Période 3'), ('P4', 'Période 4'), ('P5', 'Période 5'), ('P6', 'Période 6')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10)),
                ('creneau', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', '3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6')], max_length=2)),
                ('semaine', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='conflitgroupe',
            name='groupe1',
        ),
        migrations.RemoveField(
            model_name='conflitgroupe',
            name='groupe2',
        ),
        migrations.RemoveField(
            model_name='disponibiliteenseignant',
            name='enseignant',
        ),
        migrations.DeleteModel(
            name='ExceptionCalendrier',
        ),
        migrations.RemoveField(
            model_name='emploitemps',
            name='semaine',
        ),
        migrations.AddField(
            model_name='affectationenseignant',
            name='creneau',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6')], default='p1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affectationenseignant',
            name='jour',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], default='Lundi', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargehebdomadaire',
            name='reconduction_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconductions', to='app.chargehebdomadaire'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_groupes', to='app.groupe'),
        ),
        migrations.AlterField(
            model_name='affectationenseignant',
            name='type_cours',
            field=models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques')], max_length=2),
        ),
        migrations.AlterField(
            model_name='chargehebdomadaire',
            name='heures_cm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chargehebdomadaire',
            name='heures_td',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chargehebdomadaire',
            name='heures_tp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chargehebdomadaire',
            name='semaine',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='creneau',
            field=models.CharField(choices=[('P1', 'Période 1'), ('P2', 'Période 2'), ('P3', 'Période 3'), ('P4', 'Période 4'), ('P5', 'Période 5'), ('P6', 'Période 6')], max_length=2),
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='jour',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='groupematiere',
            unique_together={('groupe', 'matiere')},
        ),
        migrations.AddConstraint(
            model_name='affectationenseignant',
            constraint=models.UniqueConstraint(fields=('enseignant', 'jour', 'creneau'), name='unique_enseignant_creneau_affectation'),
        ),
        migrations.AddConstraint(
            model_name='emploitemps',
            constraint=models.UniqueConstraint(fields=('enseignant', 'jour', 'creneau'), name='unique_enseignant_creneau_emploi'),
        ),
        migrations.AddConstraint(
            model_name='emploitemps',
            constraint=models.UniqueConstraint(fields=('groupe', 'jour', 'creneau'), name='unique_groupe_creneau'),
        ),
        migrations.AlterUniqueTogether(
            name='calendrier',
            unique_together={('semaine', 'jour')},
        ),
        migrations.AddField(
            model_name='contraintehoraire',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.groupe'),
        ),
        migrations.AddField(
            model_name='contraintehoraire',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.matiere'),
        ),
        migrations.AddField(
            model_name='disponibilite',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='app.enseignant'),
        ),
        migrations.DeleteModel(
            name='ConflitGroupe',
        ),
        migrations.DeleteModel(
            name='DisponibiliteEnseignant',
        ),
        migrations.AddConstraint(
            model_name='contraintehoraire',
            constraint=models.UniqueConstraint(fields=('groupe', 'matiere', 'jour', 'creneau'), name='unique_contrainte_horaire'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilite',
            unique_together={('enseignant', 'jour', 'creneau', 'semaine')},
        ),
    ]
