# Generated by Django 5.1.7 on 2025-03-09 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_calendrier_contraintehoraire_disponibilite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('type_salle', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='emploitemps',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.salle'),
        ),
        migrations.AddConstraint(
            model_name='emploitemps',
            constraint=models.UniqueConstraint(fields=('salle', 'jour', 'creneau'), name='unique_salle_creneau'),
        ),
    ]
