# Generated by Django 5.1.7 on 2025-03-09 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_salle_emploitemps_salle_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emploitemps',
            name='unique_enseignant_creneau_emploi',
        ),
        migrations.RemoveConstraint(
            model_name='emploitemps',
            name='unique_groupe_creneau',
        ),
        migrations.RemoveConstraint(
            model_name='emploitemps',
            name='unique_salle_creneau',
        ),
        migrations.AddField(
            model_name='emploitemps',
            name='semaine',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='calendrier',
            name='semaine',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='chargehebdomadaire',
            name='semaine',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='contraintehoraire',
            name='creneau',
            field=models.CharField(choices=[('P1', 'Période 1'), ('P2', 'Période 2'), ('P3', 'Période 3'), ('P4', 'Période 4'), ('P5', 'Période 5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='disponibilite',
            name='semaine',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='emploitemps',
            name='creneau',
            field=models.CharField(choices=[('P1', 'Période 1'), ('P2', 'Période 2'), ('P3', 'Période 3'), ('P4', 'Période 4'), ('P5', 'Période 5')], max_length=2),
        ),
        migrations.AddConstraint(
            model_name='emploitemps',
            constraint=models.UniqueConstraint(fields=('enseignant', 'jour', 'creneau', 'semaine'), name='unique_enseignant_creneau_emploi'),
        ),
        migrations.AddConstraint(
            model_name='emploitemps',
            constraint=models.UniqueConstraint(fields=('groupe', 'jour', 'creneau', 'semaine'), name='unique_groupe_creneau'),
        ),
        migrations.AddConstraint(
            model_name='emploitemps',
            constraint=models.UniqueConstraint(fields=('salle', 'jour', 'creneau', 'semaine'), name='unique_salle_creneau'),
        ),
    ]
